export const main: string;
export const breadcrumbsContainer: string;
export const grid: string;
export const purchaseGrid: string;
export const buyTokens: string;
export const timeRemaining: string;
export const tokensRemaining: string;
export const previousSales: string;
export const chat: string;
